apiVersion: v1
kind: Pod
metadata:
  name: ml-app

spec:

  nodeSelector:
    hardware: gpu

  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

  containers:
  - name: app
    image: nginx