
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest

metadata:
  name: pradeep

spec:

  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FEQ0NBVkFDQVFBd0l6RVFNQTRHQTFVRUF3d0hjSEpoWkdWbGNERVBNQTBHQTFVRUNnd0daR1YyVDNCegpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXU1OVRLRWtsSGwyVXNrQXdXZ3NkCk9lenZ6TmxkMlFYanpOTlExQlBGNm9hbEJHM2VUM29HV2hEakREMVJOa3VnVFFuUllaQWtSR1NqQmhHZGZ4SFkKcTMzTWkxcXVLQnlFQ1FIeVZicGh4cVh6aEx3TjJVTkNRaThGektiNXpNY3lMa3AxdUxqRmxvcm45UHh4UllTbgorM0NkOXljUmRqRVQyRStyNkQyZ2ZUNGFtSVR5eTQ3NElrOVBESnRJVUJGVjlHOVJ4NHJiTDVFOEZNSnZKejRwCkVrQUVXM29xM2FNVWxNYzBoNlVvQm1hYVljY3VWaHc2WnlCeWhMUHVRTjhxWCtiQXcxV1UxeEpRdG8yQWI3VWkKZWwxenRkQit1eENTcUZidTFIZEtYUzUxbjM4ZVZQL3VRaUgzL29IcnBweDgxckdlcVZ4Mk4zZTlLZHFTelc3SgpXUUlEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR1ZWa21xYTV2cGNoTnUxRXBCL0FlRFc2Tk9DCkZuNVUzcTlZc0VPWjdsSi83ZnlwWFJ3M2lXRDRCamQ3OGt1d0cydnA1VnBHVEcybTBzUzE5SFBLOXBqQlFSYXcKdTBLU0R1eWEvMEZwVFQ5Tlo2QVlKMGhuWVdkT3ZUL3FKVTYvUXlySHdXSVhnSmVqaHR0UStoWXBSVDA3VlQ3UgoyWEZMcWhUbXZRNUdWRjgzSmNUTGpQak1UM1pQVit2S2tXOWR2UjVkWmNYWnlFdXZVN0J6THUwQjEvZGY4VFJFCjdlNHdOZExxWE5UOWxwNmxPNzFhYWNFNUdIQmlVaGtKaHJkanFPR1QvYk9zcnJtTzQ3cHphNHRjNm9BakJMLzEKTkpEUlA2SEhXS3FqQ1R0NndlcHArS1pDT1dwVFdKMXVpRk4wdHduMnc5WDFXVkIrMmx5V2huWGVDenc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=


  signerName: kubernetes.io/kube-apiserver-client

  expirationSeconds: 31536000

  usages:

  - digital signature

  - key encipherment

  - client auth