apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest

metadata:
  name: alice

spec:

  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FqQ0NBVklDQVFBd0pURU9NQXdHQTFVRUF3d0ZZV3hwWTJVeEV6QVJCZ05WQkFvTUNtUmxkbVZzYjNCbApjbk13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGtSYWlPaFlBbm9tc3Q2dFVXClRabUdrWWgxYWNmN0tad3dHZjUwQ2pjNTY0ZUdWRm53QXVpc1Uwc1VQby8zVllrTWxaSHFRellzNHdLSm1NcE0KYTlTUm1aTDlWVStuektNMUNoV1NUNkhGY2hCNjlneXJFREdVSWdoUmplZGNrb3o2Q2FxczRxSU9mTkRKQ0hQTQplNEFucEdUVWNoeDVEcU8yRXArWnA5ZzVwNS92SHNvU2pMeTc0MGcyeUJhTysrS0loUG5iM2liQ21QRDUrNTlqCnZ1dlpMamlZemRpUEl3dUJjYVFTRkhrQTBTckNyVnRGa2h0MTNLc3NDd2h1M2JHeU5BL1VHblFkK0FsYzBHblAKTFpIM09wS1JTUUZBdHV6QW5OTmJ4TW9NRW1uMmRuVmJqZjBvT3ZtekU4MTFJSXhsUFZCbWlSSTlXSzZxUzZPaApkT0RUQWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcEY0LzBvUHNXcEVVRHNxdDRSVlQvemxRClFkTU1rekJpWkxnZSs0Mjc4Mi9WaXJlRWN0NmxWZFBtL3NjNHpsN1RLeXJjOVFsbXM1em40cFQwM21aZlJXR2MKTERFbGxxMWI0bkxmVi9vT1JLejFValp6b2Vad2RFeHF0THFGMlNPcGZoakRmMWxQTzdZTmtUMVNkbWZYVmtiRAorYy9lajArMm5VdmFTaGYwdDVxeExreDNMUExkcm13WEhaVHlELzBlbzM4Qmw0aDljMmJZU3dDNWVMN05nbWRtCkpYekFXcmNlVnc3aVJZanFWdWtvMnV1eklDREtBNWtNeVdPOWN3UFJvOXUvYUpnVHdaWkxtKzVyQjJYRndnMksKeTdXM0lnSDNSb0VDcGtTbndrYVRIdUlHTVIvTmtWVlozNGFPOHVZSUczYXRDeTdFQWYwUXlWdThlVGtHRnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K

  signerName: kubernetes.io/kube-apiserver-client

  usages:

  - client auth