apiVersion: certificates.k8s.io/v1

kind: CertificateSigningRequest

metadata:
  name: rahul

spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZjbUZvZFd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFES0xmakFBU2JnTmRaUlBEK3RXb2NtNzdPUDlqR2wxdWIxWDlNS0duL3kxV0pPCldBNTMrZWlDa1BMSGtZdkFrdG9QS21DQ21qZ09lZjN1L1dyczlURFdhbDQ2cm1zeDZkTU5pZDBqdFgvQmhiOW4KK1o2NHMzU1NnOGhxTlNPUGhZMTdwUEtNLzE0Y2lPem8rT3lXVktMbitSQ1ptaUxrS29QNXE5TThnZFpUN2ptdwo1MDI4ZGhQM0M4akxYYWVaaVVYbDdVRGV0RHliNDQzZGxIOFRsbEk4czFNMzlvWStwUWhDbzc0bkY3eHNzcGFOCnBaaDR1Y3MxSTRwYnVIZWF2NWZsQ3d4SnlzS3dqaDFIVGtoNm1iSktXQ3dFNXMyRjQza2RPendvSFBnQy9MQXgKM2c3Zm5kNTQ0eGFleHV5eTc4SXpxNUxvMHBscmJyZUlIN2NPQXF1UEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFhenRXMU1icUF4ZmdhdVJpMW1rVDg4SkJQL2dIR0J5REV4UGp4eXVpeFVJM0VXYUVlR1ZJCmZ3UVpnSVpMd3lGSE9Bd0pnSFVpMUdYRHp1Sk4zQlhtNzNkclRnN25kcHJ3WWgxSmJZbHg5ZWM1NTI2eG9OeW8KVm83RDVhNVBSd3MxclRGQjQ5OXdvaGlxb1dLeEpxQnhoTGxnR09jYlBoanJjUlZqZVRweVFIM1Rlb29WNFByWQp5c3lLb2VYY2lQU1NLYm8xdlFpN3FFRlBUclFTdzJhZFplTlVlKzRsSFU0cXJlT0VPTGphaUgvYnBoTjVBUGJOCjFMMlo3UU0wR1NveEd0TjJXNGFaMXR2N3pGZit4WVZhdncyZWF2TDRTc1E4dWsrcG16Yi85RExiMlp5T0pnNWsKQ3VOWm1Ybjd3T3lwd2JRNWpKU00xbG9Na2d4MjRhTEZBZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client

  expirationSeconds: 31536000

  usages:
    - digital signature

    - key encipherment

    - client auth