

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JqQ0NBVllDQVFBd0tURVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNUk13RVFZRFZRUUtEQXBrWlhabApiRzl3WlhKek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd2ppemV6SzlCR1NHCi9HU3pNSkZSc1JBYWxoN0ZuM0lkcGpqb0dQemxxOTdhS1hoeW9sN25WVUFlbm1jSFhRbG8xZFhrbkw3cHRoaC8KUTlVK2dHc2VxRkQ3K0swOCs2eVBSQXNLUXl3RmROT3FmdElHQ29yQlFTQ0hoYTIxbWoxS0grNWpMWnRKNXI5SgpFdVFVNm9nZVIvU2xkdXJ6c1lZMGVYZVNqdjZnbURtMW4xTlcrNTZMeXRsR3dUVHZMczlZd2Y1aktJZW1EZmI3ClVKU2NoT0Ztc21oTFhLbUExS2tFRjQ1aEhyeGxsYXhwMnVqanBKNnA2UytYNjlTVGVTOEF3SjVuTjBRcm5Ga3MKZjhZbWNYZU93MG1VVHRjWkxVRlRaZk5NQUM5bmtkdnRxSUpHQVpLeG5aR28ySFBiTE5EU2xBSzRIRURHSG5sWgpSVVJHZHEyZjZ3SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMWm95QUN5UVF2RnE1d3JLWHBQCjJBeVJNYnNHY3hhTHdJUnRhaGZFeWk3aFdzTTlZMlB4aVljQkpjblcyZURoRERJRk1DekJRK3l0dm5LWExDVjYKbUtYblNFQ0JXaUNOeHI3UG5TYmlwaGdQL0NlS0hINm9ROHZrOU0zQ0xheDE2WDRrVTV1QjZKbC8wRmFkT0EyKwpxdGpJNkpLU3RJQlM1aGRrcndYRFVjTWwwaFBhTlA4S2lJam9Lc0FEdHk4K1hIS08vbCtIaFFEbGNQdHlZVkJrClVWNnVMWFJleW9nZWZnd2xIei95Qlh6QTEwT2YxdVFsTVlybEVUTG5pWGRsa1B0RWdPdks5TGMzMGs2b1ppVkEKTjJMc3ZTYVpuTTRkaDkzcWFwL25QcWhSeFkwZjVtZ2FMR2hUamRQWHVVVy9tcWRrMUdOaW9TdjdNSkNXQlFzQgpvRjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000
  usages:
  - client auth