apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-demo2

spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: frontend
            operator: In
            values:
            - "true"

  containers:
  - name: nginx
    image: nginx