# apiVersion: apps/v1
# kind: Deployment

# metadata:
#   name: spring-health

# spec:
#   replicas: 2

#   selector:
#     matchLabels:
#       app: spring-health

#   template:

#     metadata:
#       labels:
#         app: spring-health

#     spec:

#       containers:

#       - name: app

#         image: spring-health:1.0

#         imagePullPolicy: Never

#         ports:

#         - containerPort: 8080


apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-health

spec:
  replicas: 2

  selector:
    matchLabels:
      app: spring-health

  template:
    metadata:
      labels:
        app: spring-health

    spec:
      containers:
        - name: app
          image: spring-health:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3